//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub mod prelude;

pub mod asset_type;
pub mod asset;
pub mod location_type;
pub mod location;
pub mod address;
pub mod maintenance_schedule;
pub mod manufacturer;
pub mod notification;
pub mod notification_delivery_log;
pub mod notification_template;
pub mod permission;
pub mod permission_log;
pub mod role;
pub mod role_hierarchy;
pub mod task;
pub mod temp_role_elevation;
pub mod user;
pub mod user_notification_preferences;
pub mod user_preferences;
pub mod user_role;
pub mod vendor;
pub mod vendor_category;
pub mod work_order;

seaography::register_entity_modules!([
    asset_type,
    asset,
    location_type,
    location,
    address,
    maintenance_schedule,
    manufacturer,
    notification,
    notification_delivery_log,
    notification_template,
    permission,
    permission_log,
    role,
    role_hierarchy,
    task,
    temp_role_elevation,
    user,
    user_notification_preferences,
    user_preferences,
    user_role,
    vendor,
    vendor_category,
    work_order,
]);
