//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "notification")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub template_id: Uuid,
    pub recipient_id: Uuid,
    pub context: Option<Json>,
    pub severity: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub delivered_channels: Option<Json>,
    pub read_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::notification_delivery_log::Entity")]
    NotificationDeliveryLog,
    #[sea_orm(
        belongs_to = "super::notification_template::Entity",
        from = "Column::TemplateId",
        to = "super::notification_template::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    NotificationTemplate,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::RecipientId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::notification_delivery_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationDeliveryLog.def()
    }
}

impl Related<super::notification_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotificationTemplate.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::notification_delivery_log::Entity")]
    NotificationDeliveryLog,
    #[sea_orm(entity = "super::notification_template::Entity")]
    NotificationTemplate,
    #[sea_orm(entity = "super::user::Entity")]
    User,
}
