//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::asset::Entity as Asset;
pub use super::location::Entity as Location;
pub use super::maintenance_schedule::Entity as MaintenanceSchedule;
pub use super::notification::Entity as Notification;
pub use super::notification_delivery_log::Entity as NotificationDeliveryLog;
pub use super::notification_template::Entity as NotificationTemplate;
pub use super::permission::Entity as Permission;
pub use super::permission_log::Entity as PermissionLog;
pub use super::role::Entity as Role;
pub use super::role_hierarchy::Entity as RoleHierarchy;
pub use super::task::Entity as Task;
pub use super::temp_role_elevation::Entity as TempRoleElevation;
pub use super::user::Entity as User;
pub use super::user_notification_preferences::Entity as UserNotificationPreferences;
pub use super::user_preferences::Entity as UserPreferences;
pub use super::user_role::Entity as UserRole;
pub use super::vendor::Entity as Vendor;
pub use super::vendor_category::Entity as VendorCategory;
pub use super::work_order::Entity as WorkOrder;
